[package]
name = "cargo-mutagen"
version = "0.1.0"
authors = ["Hmvp <github@hmvp.nl>", "Andre Bogus <bogusandre@gmail.com>"]
description = "Mutation testing for Rust â€“ Runner"
repository = "https://github.com/llogiq/mutator"
license = "Apache-2.0/MIT"

[dependencies]
json = "0.11.12"
