[package]
name = "cargo-mutagen"
version = "0.2.0"
authors = ["Andre Bogus <bogusandre@gmail.com>", "Samuel Pilz <samuel.pilz@posteo.net>"]
edition = "2018"

[dependencies]
json = "0.11"
failure = "0.1"
wait-timeout = "0.1.5"
serde_json = "1.0"
mutagen-core = { path = "../mutagen-core"}
console = "0.9.1"
humantime = "1.3.0"

[badges]
travis-ci = { repository = "llogiq/mutagen", branch = "master" }

[lib]
doctest = false
